version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: ./d1.df
    image: frontend:v1.0
    container_name: c1
    ports:
    - "8090:8090"
    environment:
      - servername=backend
      - username=postgres
      - password=1234
    depends_on:
    - backend
       
  backend:
    build:
      context: .
      dockerfile: ./db.df
    image: backend:v1.1
    container_name: db1
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=empdb
      - POSTGRES_PASSWORD=1234
